services:
  - type: web
    name: medical-awareness-ai-system
    env: python
    plan: free

   buildCommand: pip install --upgrade pip && pip install -r requirements.txt

    startCommand: gunicorn app:app

    envVars:
      - key: GEMINI_API_KEY
        sync: false

      - key: SERPER_API_KEY
        sync: false

      - key: PORT
        value: 10000